package megvii.testfacepass.beans;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BEN_DI_USER_IN_FO".
*/
public class BenDiUserInFoDao extends AbstractDao<BenDiUserInFo, Long> {

    public static final String TABLENAME = "BEN_DI_USER_IN_FO";

    /**
     * Properties of entity BenDiUserInFo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Xingbie = new Property(2, int.class, "xingbie", false, "XINGBIE");
        public final static Property Beizhu = new Property(3, String.class, "beizhu", false, "BEIZHU");
    }


    public BenDiUserInFoDao(DaoConfig config) {
        super(config);
    }
    
    public BenDiUserInFoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BEN_DI_USER_IN_FO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"XINGBIE\" INTEGER NOT NULL ," + // 2: xingbie
                "\"BEIZHU\" TEXT);"); // 3: beizhu
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BEN_DI_USER_IN_FO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BenDiUserInFo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getXingbie());
 
        String beizhu = entity.getBeizhu();
        if (beizhu != null) {
            stmt.bindString(4, beizhu);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BenDiUserInFo entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getXingbie());
 
        String beizhu = entity.getBeizhu();
        if (beizhu != null) {
            stmt.bindString(4, beizhu);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public BenDiUserInFo readEntity(Cursor cursor, int offset) {
        BenDiUserInFo entity = new BenDiUserInFo( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getInt(offset + 2), // xingbie
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // beizhu
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BenDiUserInFo entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setXingbie(cursor.getInt(offset + 2));
        entity.setBeizhu(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BenDiUserInFo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BenDiUserInFo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BenDiUserInFo entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
